### ISSUE TITLE
Cannot find module 'connect'

### ISSUE THREAD

**Issue by c4milo** [ciaranj/connect-auth#50]
I am getting this error trying to start up my server.js. 

It seems like we need to declare connect as dependency in package.json so that npm can install connect-auth correctly

**Comment by c4milo** [comment]
more info

NODE_ENV=test node server.js 

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'connect'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at require (module.js:351:19)
    at Object.<anonymous> (/Users/camilo/Dropbox/Development/foo/bar/node_modules/connect-auth/lib/index.js:9:14)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:351:19)
    at Object.<anonymous> (/Users/camilo/Dropbox/Development/foo/bar/server.js:5:12)

node --version 
v0.4.8

npm --version 
1.0.10

**Comment by ciaranj** [comment]
Closed by (your) pull request : https://github.com/ciaranj/connect-auth/pull/52 (thank you)
